services:
  - type: web
    name: customer-call-summarizer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.headless true"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ZAPIER_NLA_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
